# Generated by Django 2.2.3 on 2021-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroComprado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adquisicion', models.DateField()),
                ('cantidad_venta', models.IntegerField()),
                ('cantidad_compra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LibroUsado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateField()),
                ('cantidad_venta', models.IntegerField()),
                ('cantidad_compra', models.IntegerField()),
            ],
        ),
    ]
