# Generated by Django 2.2.3 on 2021-02-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Documento'),
        ),
    ]
