# Generated by Django 2.2.3 on 2021-02-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_auto_20210221_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=15),
        ),
    ]
