# Generated by Django 2.2.3 on 2021-02-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
