# Generated by Django 2.2.3 on 2021-03-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_factura_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_exento',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
