# Generated by Django 2.2.3 on 2021-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_factura_total_exento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.IntegerField(choices=[('1', 'Compra'), ('2', 'Venta')], default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_exento',
            field=models.FloatField(default=0),
        ),
    ]
