# Generated by Django 2.2.3 on 2021-06-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_auto_20210408_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_exento',
            field=models.FloatField(),
        ),
    ]
